name: Apache Static Site CICD

on:
  push:
    branches: [main]
    paths:
      - 'apache-site/**'
      - '.github/workflows/apache-cicd.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Apache image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apache-site ./apache-site

      - name: Push Apache image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apache-site:latest

  deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Apache image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/apache-site:latest

      - name: Stop old Apache container
        run: docker rm -f apache-site-container || true

      - name: Run Apache container
        run: docker run -d -p 8080:80 --name apache-site-container ${{ secrets.DOCKER_USERNAME }}/apache-site:latest
